on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Format
      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
    - name: Build
      run: go build .
